### ISSUE TITLE
Not working MacBook Pro Mid-2012

### ISSUE THREAD

**Issue by ardacebi** [dabrain13/DarkBoot-NVRAM#1]
On my MacBook Pro Mid 2012 running macOS Sierra, I can move the file to the LaunchDeamonds file but I can't run the command on the terminal:

`sudo launchctl load /Library/LaunchDaemons/com.dabrain13.darkboot.plist`

**I Enter the password after writing the command**

It gives the following error:

`/Library/LaunchDaemons/com.dabrain13.darkboot.plist: Path had bad ownership/permissions
`

Does this mean it is done or an error that explains it failed?

Thanks,
Arda

**Comment by marco2012** [comment]
You have to set the correct permissions before using _launchctl_ 

In terminal, type:
```
sudo chmod 600 /Library/LaunchDaemons/com.dabrain13.darkboot.plist
sudo chown root /Library/LaunchDaemons/com.dabrain13.darkboot.plist
```
then you can use _launchctl_ :
`sudo launchctl load /Library/LaunchDaemons/com.dabrain13.darkboot.plist`
